
"""
utils.py
--------
Utility functions for logging and other shared operations in MiniVault API.
"""

import json
from datetime import datetime
from pathlib import Path

# Directory for storing log files
LOGS_DIR = Path("logs")
LOGS_DIR.mkdir(exist_ok=True)
# Path to the log file (JSON Lines format)
LOG_FILE = LOGS_DIR / "log.jsonl"

def log_interaction(prompt: str, response: str) -> None:
    """
    Log the prompt and response interaction to a JSONL file.

    Args:
        prompt (str): The prompt sent to the LLM or stub.
        response (str): The response generated by the LLM or stub.
    """
    log_entry = {
        "timestamp": datetime.utcnow().isoformat(),
        "prompt": prompt,
        "response": response,
        "response_length": len(response)
    }
    # Append the log entry as a JSON line
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(json.dumps(log_entry) + "\n")
